# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: jackiescanlon.github.io

# User settings
username: Jackie Scanlon
user_description: I'm a driven software engineer excited about future mobility & its use of robot autonomy!
user_title: Software Engineer
email: jackiescanlon13@gmail.com
github_username:  jackiescanlon

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
